<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-20T16:10:21 EDT" name="Suite" finished-at="2024-08-20T16:11:33 EDT" duration-ms="71945">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidations()[pri:0, instance:AutomationFramework.Test.ErrorValidationsTest@f58853c]" name="LoginErrorValidations" class="AutomationFramework.Test.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:AutomationFramework.Test.SubmitOrderTest@3de8f619]" name="submitOrder" class="AutomationFramework.Test.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-08-20T16:10:21 EDT" name="Submit Order Test" finished-at="2024-08-20T16:11:24 EDT" duration-ms="63558">
      <class name="AutomationFramework.Test.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationFramework.Test.SubmitOrderTest@3de8f619]" started-at="2024-08-20T16:10:21 EDT" name="launchApplication" finished-at="2024-08-20T16:10:36 EDT" duration-ms="15074" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:AutomationFramework.Test.SubmitOrderTest@3de8f619]" started-at="2024-08-20T16:10:36 EDT" name="submitOrder" data-provider="getData" finished-at="2024-08-20T16:11:04 EDT" duration-ms="27448" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Abc$1234, product=ZARA COAT 3, email=organic.test@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[element click intercepted: Element is not clickable at point (943, 653)
  (Session info: chrome=127.0.6533.120)
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d388ff98e24f4cbe8983bdd685724974, clickElement {id=f.ABD09BC0E89EFED6AC1635959592C7DE.d.BE1963F8B55154AAF93D585DD6B4895E.e.121}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 127.0.6533.120, chrome: {chromedriverVersion: 127.0.6533.119 (bdef6783a05..., userDataDir: C:\WINDOWS\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:57469}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57469/devtoo..., se:cdpVersion: 127.0.6533.120, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (d388ff98e24f4cbe8983bdd685724974)] -> xpath: //a[text()='Place Order ']]
Session ID: d388ff98e24f4cbe8983bdd685724974]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element is not clickable at point (943, 653)
  (Session info: chrome=127.0.6533.120)
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d388ff98e24f4cbe8983bdd685724974, clickElement {id=f.ABD09BC0E89EFED6AC1635959592C7DE.d.BE1963F8B55154AAF93D585DD6B4895E.e.121}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 127.0.6533.120, chrome: {chromedriverVersion: 127.0.6533.119 (bdef6783a05..., userDataDir: C:\WINDOWS\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:57469}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57469/devtoo..., se:cdpVersion: 127.0.6533.120, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (d388ff98e24f4cbe8983bdd685724974)] -> xpath: //a[text()='Place Order ']]
Session ID: d388ff98e24f4cbe8983bdd685724974
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at AutomationFramework.pageobjects.CheckoutPage.submitOrder(CheckoutPage.java:51)
at AutomationFramework.Test.SubmitOrderTest.submitOrder(SubmitOrderTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:AutomationFramework.Test.SubmitOrderTest@3de8f619]" started-at="2024-08-20T16:11:04 EDT" name="tearDown" finished-at="2024-08-20T16:11:04 EDT" duration-ms="56" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationFramework.Test.SubmitOrderTest@3de8f619]" started-at="2024-08-20T16:11:04 EDT" name="launchApplication" finished-at="2024-08-20T16:11:12 EDT" duration-ms="8336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:AutomationFramework.Test.SubmitOrderTest@3de8f619]" started-at="2024-08-20T16:11:12 EDT" name="submitOrder" data-provider="getData" finished-at="2024-08-20T16:11:24 EDT" duration-ms="11875" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Xyz$1234, product=ADIDAS ORIGINAL, email=artificial.test@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at AutomationFramework.Test.SubmitOrderTest.submitOrder(SubmitOrderTest.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:AutomationFramework.Test.SubmitOrderTest@3de8f619]" started-at="2024-08-20T16:11:24 EDT" name="tearDown" finished-at="2024-08-20T16:11:24 EDT" duration-ms="70" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:AutomationFramework.Test.SubmitOrderTest@3de8f619]" started-at="2024-08-20T16:11:24 EDT" name="OrderHistoryTest" finished-at="2024-08-20T16:11:24 EDT" depends-on-methods="AutomationFramework.Test.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AutomationFramework.Test.SubmitOrderTest.OrderHistoryTest() on instance AutomationFramework.Test.SubmitOrderTest@3de8f619 depends on not successfully finished methods 
[AutomationFramework.Test.SubmitOrderTest.submitOrder() on instance AutomationFramework.Test.SubmitOrderTest@3de8f619]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AutomationFramework.Test.SubmitOrderTest.OrderHistoryTest() on instance AutomationFramework.Test.SubmitOrderTest@3de8f619 depends on not successfully finished methods 
[AutomationFramework.Test.SubmitOrderTest.submitOrder() on instance AutomationFramework.Test.SubmitOrderTest@3de8f619]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- AutomationFramework.Test.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2024-08-20T16:10:21 EDT" name="Error Validations Test" finished-at="2024-08-20T16:11:33 EDT" duration-ms="71945">
      <class name="AutomationFramework.Test.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationFramework.Test.ErrorValidationsTest@f58853c]" started-at="2024-08-20T16:10:21 EDT" name="launchApplication" finished-at="2024-08-20T16:10:37 EDT" duration-ms="15879" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidations()[pri:0, instance:AutomationFramework.Test.ErrorValidationsTest@f58853c]" started-at="2024-08-20T16:10:37 EDT" name="LoginErrorValidations" finished-at="2024-08-20T16:10:50 EDT" duration-ms="13037" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidations -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:AutomationFramework.Test.ErrorValidationsTest@f58853c]" started-at="2024-08-20T16:10:50 EDT" name="tearDown" finished-at="2024-08-20T16:10:50 EDT" duration-ms="562" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationFramework.Test.ErrorValidationsTest@f58853c]" started-at="2024-08-20T16:10:50 EDT" name="launchApplication" finished-at="2024-08-20T16:10:57 EDT" duration-ms="6797" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidations()[pri:0, instance:AutomationFramework.Test.ErrorValidationsTest@f58853c]" started-at="2024-08-20T16:10:57 EDT" name="ProductErrorValidations" finished-at="2024-08-20T16:11:33 EDT" duration-ms="35503" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidations -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:AutomationFramework.Test.ErrorValidationsTest@f58853c]" started-at="2024-08-20T16:11:33 EDT" name="tearDown" finished-at="2024-08-20T16:11:33 EDT" duration-ms="103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- AutomationFramework.Test.ErrorValidationsTest -->
    </test> <!-- Error Validations Test -->
  </suite> <!-- Suite -->
</testng-results>
